title: TheHosts.Club
author: Marcus Bearden
email: marcus@thehosts.club
description: > # this means to ignore newlines until "baseurl:"
  TheHosts.Club was started out of a personal need for good advice on entertaining
  and hosting events.  We are passionate about bringing joy to our friends and family
  and continued to struggle to find a good resource for this information.  The only
  logical step left was to start our own.  Welcome to our home!

# social links
twitter_username: thehostsclub
github_username:  tasogarre

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
